import { defineView, ViewType } from 'twenty-sdk/define';
import {
  INSURANCE_POLICY,
  POLICIES_ALL,
  P_PERIOD_END,
  P_PERIOD_START,
  P_PLATE,
  P_POLICY_NO,
  P_PREMIUM,
  P_QUOTE_REF,
  P_STATUS,
  P_VEHICLE_MAKE,
  VIEW_POLICIES_ALL_COL0,
  VIEW_POLICIES_ALL_COL1,
  VIEW_POLICIES_ALL_COL2,
  VIEW_POLICIES_ALL_COL3,
  VIEW_POLICIES_ALL_COL4,
  VIEW_POLICIES_ALL_COL5,
  VIEW_POLICIES_ALL_COL6,
  VIEW_POLICIES_ALL_COL7,
} from 'src/constants/universal-identifiers';

export default defineView({
  universalIdentifier: POLICIES_ALL,
  name: 'All policies',
  objectUniversalIdentifier: INSURANCE_POLICY,
  type: ViewType.TABLE,
  icon: 'IconShieldCheck',
  position: 0,
  fields: [
    { universalIdentifier: VIEW_POLICIES_ALL_COL0, fieldMetadataUniversalIdentifier: P_POLICY_NO, position: 0, isVisible: true, size: 160 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL1, fieldMetadataUniversalIdentifier: P_STATUS, position: 1, isVisible: true, size: 130 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL2, fieldMetadataUniversalIdentifier: P_PLATE, position: 2, isVisible: true, size: 140 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL3, fieldMetadataUniversalIdentifier: P_PREMIUM, position: 3, isVisible: true, size: 150 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL4, fieldMetadataUniversalIdentifier: P_PERIOD_START, position: 4, isVisible: true, size: 130 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL5, fieldMetadataUniversalIdentifier: P_PERIOD_END, position: 5, isVisible: true, size: 130 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL6, fieldMetadataUniversalIdentifier: P_QUOTE_REF, position: 6, isVisible: true, size: 160 },
    { universalIdentifier: VIEW_POLICIES_ALL_COL7, fieldMetadataUniversalIdentifier: P_VEHICLE_MAKE, position: 7, isVisible: true, size: 140 },
  ],
});
