import {
  definePageLayout,
  PageLayoutTabLayoutMode,
  AggregateOperations,
} from 'twenty-sdk/define';
import {
  COMMISSION,
  CM_AMOUNT,
  CM_STATUS,
  INSURANCE_CLAIM,
  C_CLAIM_REF,
  C_RESERVE,
  C_STATUS,
  INSURANCE_PAYMENT,
  PM_AMOUNT,
  PM_PAYMENT_REF,
  PM_PROVIDER,
  PM_STATUS,
  INSURANCE_POLICY,
  P_PERIOD_START,
  P_POLICY_NO,
  P_PREMIUM,
  P_STATUS,
  INSURANCE_QUOTE,
  Q_CHANNEL,
  Q_PREMIUM,
  Q_REFERENCE,
  Q_STATUS,
  PROTECTA_DASHBOARD,
  PROTECTA_DASHBOARD_TAB_FINANCE,
  PROTECTA_DASHBOARD_TAB_OVERVIEW,
  PROTECTA_DASHBOARD_TAB_RISK,
  PROTECTA_DASHBOARD_TAB_SALES,
  PROTECTA_DASHBOARD_W_CLAIMS_BY_STATUS,
  PROTECTA_DASHBOARD_W_CLAIMS_RESERVE,
  PROTECTA_DASHBOARD_W_COMMISSIONS,
  PROTECTA_DASHBOARD_W_PENDING,
  PROTECTA_DASHBOARD_W_POLICIES,
  PROTECTA_DASHBOARD_W_POLICIES_BY_STATUS,
  PROTECTA_DASHBOARD_W_POLICIES_TREND,
  PROTECTA_DASHBOARD_W_PREMIUM,
  PROTECTA_DASHBOARD_W_QUOTES,
  PROTECTA_DASHBOARD_W_QUOTES_BY_CHANNEL,
  PROTECTA_DASHBOARD_W_QUOTES_BY_STATUS,
  PROTECTA_DASHBOARD_W_PAYMENTS_BY_PROVIDER,
  PROTECTA_DASHBOARD_W_EXPIRING,
  PROTECTA_DASHBOARD_W_PENDING_PAYMENTS_TABLE,
} from 'src/constants/universal-identifiers';
import { POLICIES_EXPIRING } from 'src/constants/universal-identifiers';
import { PAYMENTS_PENDING } from 'src/constants/universal-identifiers';

export default definePageLayout({
  universalIdentifier: PROTECTA_DASHBOARD,
  name: 'Protecta Bode Ops',
  type: 'DASHBOARD',
  tabs: [
    {
      universalIdentifier: PROTECTA_DASHBOARD_TAB_OVERVIEW,
      title: 'Overview',
      position: 0,
      icon: 'IconDashboard',
      layoutMode: PageLayoutTabLayoutMode.GRID,
      widgets: [
        // Row 0: 4 KPIs
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_QUOTES,
          title: 'Quotes (total)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_QUOTE,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 0,
            rowSpan: 2,
            columnSpan: 3,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: Q_REFERENCE,
            aggregateOperation: AggregateOperations.COUNT,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_POLICIES,
          title: 'Active policies',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_POLICY,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 3,
            rowSpan: 2,
            columnSpan: 3,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: P_POLICY_NO,
            aggregateOperation: AggregateOperations.COUNT,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: P_STATUS,
                  operand: 'IS',
                  value: '["ACTIVE"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_PREMIUM,
          title: 'Premium collected (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_POLICY,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 6,
            rowSpan: 2,
            columnSpan: 3,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: P_PREMIUM,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: P_STATUS,
                  operand: 'IS',
                  value: '["ACTIVE"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_PENDING,
          title: 'Pending payments',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_PAYMENT,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 9,
            rowSpan: 2,
            columnSpan: 3,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: PM_PAYMENT_REF,
            aggregateOperation: AggregateOperations.COUNT,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: PM_STATUS,
                  operand: 'IS',
                  value: '["PENDING"]',
                },
              ],
            },
          },
        },
        // Row 2: distribution
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_QUOTES_BY_STATUS,
          title: 'Quotes by status',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_QUOTE,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 2,
            column: 0,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldMetadataUniversalIdentifier: Q_REFERENCE,
            aggregateOperation: AggregateOperations.COUNT,
            groupByFieldMetadataUniversalIdentifier: Q_STATUS,
            displayLegend: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_POLICIES_BY_STATUS,
          title: 'Policies by status',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_POLICY,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 2,
            column: 6,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldMetadataUniversalIdentifier: P_POLICY_NO,
            aggregateOperation: AggregateOperations.COUNT,
            groupByFieldMetadataUniversalIdentifier: P_STATUS,
            displayLegend: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        // Row 7: provider / channel / reserve
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_PAYMENTS_BY_PROVIDER,
          title: 'Payments by provider',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_PAYMENT,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 7,
            column: 0,
            rowSpan: 5,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'BAR_CHART',
            aggregateFieldMetadataUniversalIdentifier: PM_PAYMENT_REF,
            aggregateOperation: AggregateOperations.COUNT,
            primaryAxisGroupByFieldMetadataUniversalIdentifier: PM_PROVIDER,
            layout: 'VERTICAL',
            primaryAxisOrderBy: 'FIELD_ASC',
            axisNameDisplay: 'NONE',
            color: 'auto',
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            // @ts-ignore string literal for SDK not exporting enum
            displayLegend: true,
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_QUOTES_BY_CHANNEL,
          title: 'Quotes by channel',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_QUOTE,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 7,
            column: 4,
            rowSpan: 5,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'BAR_CHART',
            aggregateFieldMetadataUniversalIdentifier: Q_REFERENCE,
            aggregateOperation: AggregateOperations.COUNT,
            primaryAxisGroupByFieldMetadataUniversalIdentifier: Q_CHANNEL,
            layout: 'VERTICAL',
            primaryAxisOrderBy: 'FIELD_ASC',
            axisNameDisplay: 'NONE',
            color: 'auto',
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_CLAIMS_BY_STATUS,
          title: 'Claims by status',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_CLAIM,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 7,
            column: 8,
            rowSpan: 5,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'BAR_CHART',
            aggregateFieldMetadataUniversalIdentifier: C_CLAIM_REF,
            aggregateOperation: AggregateOperations.COUNT,
            primaryAxisGroupByFieldMetadataUniversalIdentifier: C_STATUS,
            layout: 'VERTICAL',
            primaryAxisOrderBy: 'FIELD_ASC',
            axisNameDisplay: 'NONE',
            color: 'auto',
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        // Row 12: trend + financials
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_POLICIES_TREND,
          title: 'Policies by start month',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_POLICY,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 12,
            column: 0,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'BAR_CHART',
            aggregateFieldMetadataUniversalIdentifier: P_POLICY_NO,
            aggregateOperation: AggregateOperations.COUNT,
            primaryAxisGroupByFieldMetadataUniversalIdentifier: P_PERIOD_START,
            // @ts-ignore date grouping not typed as enum in SDK helper
            primaryAxisDateGranularity: 'MONTH',
            layout: 'VERTICAL',
            primaryAxisOrderBy: 'FIELD_ASC',
            axisNameDisplay: 'NONE',
            color: 'auto',
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_COMMISSIONS,
          title: 'Commissions payable (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: COMMISSION,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 12,
            column: 6,
            rowSpan: 5,
            columnSpan: 3,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: CM_AMOUNT,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: CM_STATUS,
                  operand: 'IS',
                  value: '["PAYABLE","ACCRUED"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_CLAIMS_RESERVE,
          title: 'Claims reserve (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_CLAIM,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 12,
            column: 9,
            rowSpan: 5,
            columnSpan: 3,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: C_RESERVE,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        // Row 17: tables
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_EXPIRING,
          title: 'Policies expiring soon',
          type: 'RECORD_TABLE',
          objectUniversalIdentifier: INSURANCE_POLICY,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 17,
            column: 0,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'RECORD_TABLE',
            viewId: POLICIES_EXPIRING,
            recordLimit: 10,
            isUIEditable: false,
          },
        },
        {
          universalIdentifier: PROTECTA_DASHBOARD_W_PENDING_PAYMENTS_TABLE,
          title: 'Payments pending',
          type: 'RECORD_TABLE',
          objectUniversalIdentifier: INSURANCE_PAYMENT,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 17,
            column: 6,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'RECORD_TABLE',
            viewId: PAYMENTS_PENDING,
            recordLimit: 10,
            isUIEditable: false,
          },
        },
      ],
    },
    {
      universalIdentifier: PROTECTA_DASHBOARD_TAB_SALES,
      title: 'Sales & Premium',
      position: 1,
      icon: 'IconCash',
      layoutMode: PageLayoutTabLayoutMode.GRID,
      widgets: [
        {
          universalIdentifier: 'a1b2c3d4-0001-4a1a-9a1a-aaaaaaaaaaaa',
          title: 'Quotes premium (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_QUOTE,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 0,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: Q_PREMIUM,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: 'b2c3d4e5-0002-4b2b-9b2b-bbbbbbbbbbbb',
          title: 'Policies premium (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_POLICY,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 4,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: P_PREMIUM,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: 'c3d4e5f6-0003-4c3c-9c3c-cccccccccccc',
          title: 'Payments collected (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_PAYMENT,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 8,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: PM_AMOUNT,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: PM_STATUS,
                  operand: 'IS',
                  value: '["CONFIRMED"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: 'd4e5f6a7-0004-4d4d-9d4d-dddddddddddd',
          title: 'Premium by channel',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_QUOTE,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 2,
            column: 0,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'BAR_CHART',
            aggregateFieldMetadataUniversalIdentifier: Q_PREMIUM,
            aggregateOperation: AggregateOperations.SUM,
            primaryAxisGroupByFieldMetadataUniversalIdentifier: Q_CHANNEL,
            layout: 'VERTICAL',
            primaryAxisOrderBy: 'VALUE_DESC',
            axisNameDisplay: 'NONE',
            color: 'auto',
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: 'e5f6a7b8-0005-4e5e-9e5e-eeeeeeeeeeee',
          title: 'Conversion — quotes → policies',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_QUOTE,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 2,
            column: 6,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldMetadataUniversalIdentifier: Q_REFERENCE,
            aggregateOperation: AggregateOperations.COUNT,
            groupByFieldMetadataUniversalIdentifier: Q_STATUS,
            displayLegend: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
      ],
    },
    {
      universalIdentifier: PROTECTA_DASHBOARD_TAB_RISK,
      title: 'Risk & Claims',
      position: 2,
      icon: 'IconAlertTriangle',
      layoutMode: PageLayoutTabLayoutMode.GRID,
      widgets: [
        {
          universalIdentifier: 'f6a7b8c9-0006-4f6f-9f6f-ffffffffffff',
          title: 'Open claims',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_CLAIM,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 0,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: C_CLAIM_REF,
            aggregateOperation: AggregateOperations.COUNT,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: C_STATUS,
                  operand: 'IS',
                  value: '["REPORTED","ASSIGNED","ASSESSED"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: '0a6b8c9d-0007-4a70-9a70-111111111111',
          title: 'Approved claims',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_CLAIM,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 4,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: C_CLAIM_REF,
            aggregateOperation: AggregateOperations.COUNT,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: C_STATUS,
                  operand: 'IS',
                  value: '["APPROVED","SETTLED"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: '1b7c9d0e-0008-4b71-9b71-222222222222',
          title: 'Loss ratio proxy (reserve / premium)',
          type: 'GRAPH',
          objectUniversalIdentifier: INSURANCE_CLAIM,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 8,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: C_RESERVE,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
      ],
    },
    {
      universalIdentifier: PROTECTA_DASHBOARD_TAB_FINANCE,
      title: 'Finance',
      position: 3,
      icon: 'IconCoin',
      layoutMode: PageLayoutTabLayoutMode.GRID,
      widgets: [
        {
          universalIdentifier: '2c8d9e0f-0009-4c72-9c72-333333333333',
          title: 'Commissions accrued (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: COMMISSION,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 0,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: CM_AMOUNT,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: CM_STATUS,
                  operand: 'IS',
                  value: '["ACCRUED"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: '3d9e0f1a-0010-4d73-9d73-444444444444',
          title: 'Commissions payable (UGX)',
          type: 'GRAPH',
          objectUniversalIdentifier: COMMISSION,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 4,
            rowSpan: 2,
            columnSpan: 4,
          },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldMetadataUniversalIdentifier: CM_AMOUNT,
            aggregateOperation: AggregateOperations.SUM,
            displayDataLabel: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
            filter: {
              recordFilters: [
                {
                  fieldMetadataUniversalIdentifier: CM_STATUS,
                  operand: 'IS',
                  value: '["PAYABLE"]',
                },
              ],
            },
          },
        },
        {
          universalIdentifier: '4e0f1a2b-0011-4d74-9d74-555555555555',
          title: 'Commissions by status',
          type: 'GRAPH',
          objectUniversalIdentifier: COMMISSION,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 2,
            column: 0,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldMetadataUniversalIdentifier: CM_AMOUNT,
            aggregateOperation: AggregateOperations.COUNT,
            groupByFieldMetadataUniversalIdentifier: CM_STATUS,
            displayLegend: true,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
        {
          universalIdentifier: '5f1a2b3c-0012-4d75-9d75-666666666666',
          title: 'Commissions by month',
          type: 'GRAPH',
          objectUniversalIdentifier: COMMISSION,
          position: {
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 2,
            column: 6,
            rowSpan: 5,
            columnSpan: 6,
          },
          configuration: {
            configurationType: 'BAR_CHART',
            aggregateFieldMetadataUniversalIdentifier: CM_AMOUNT,
            aggregateOperation: AggregateOperations.SUM,
            primaryAxisGroupByFieldMetadataUniversalIdentifier: CM_STATUS,
            layout: 'VERTICAL',
            primaryAxisOrderBy: 'VALUE_DESC',
            axisNameDisplay: 'NONE',
            color: 'auto',
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
      ],
    },
  ],
});
