import { defineObject, FieldType, NumberDataType } from 'twenty-sdk/define';
import {
  INSURANCE_POLICY,
  P_BODY_TYPE,
  P_ENGINE_CC,
  P_PERIOD_END,
  P_PERIOD_START,
  P_PLATE,
  P_POLICY_NO,
  P_PREMIUM,
  P_PROTECTA_REF,
  P_QUOTE_REF,
  P_SEATING_CAPACITY,
  P_STAMP_DUTY,
  P_STATUS,
  P_STICKER_FEES,
  P_SUM_INSURED,
  P_TOTAL_PREMIUM,
  P_TRAINING_LEVY,
  P_VAT,
  P_VEHICLE_MAKE,
  P_VEHICLE_MODEL,
} from 'src/constants/universal-identifiers';

export const INSURANCE_POLICY_UNIVERSAL_IDENTIFIER = INSURANCE_POLICY;

export default defineObject({
  universalIdentifier: INSURANCE_POLICY_UNIVERSAL_IDENTIFIER,
  nameSingular: 'insurancePolicy',
  namePlural: 'insurancePolicies',
  labelSingular: 'Insurance policy',
  labelPlural: 'Insurance policies',
  description: 'Issued Protecta Bode motor policy',
  icon: 'IconShieldCheck',
  labelIdentifierFieldMetadataUniversalIdentifier: P_POLICY_NO,
  fields: [
    {
      universalIdentifier: P_PROTECTA_REF,
      name: 'protectaRef',
      type: FieldType.TEXT,
      label: 'Protecta ref',
      description: 'Policy number',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: P_POLICY_NO,
      name: 'policyNo',
      isUnique: true,
      type: FieldType.TEXT,
      label: 'Policy no',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: P_QUOTE_REF,
      name: 'quoteRef',
      isUnique: true,
      type: FieldType.TEXT,
      label: 'Quote ref',
      icon: 'IconHash',
    },
    {
      universalIdentifier: P_STATUS,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'ACTIVE'",
      options: [
        {
          value: 'PENDING_PAYMENT',
          label: 'Pending payment',
          position: 0,
          color: 'yellow',
        },
        { value: 'ACTIVE', label: 'Active', position: 1, color: 'green' },
        { value: 'LAPSED', label: 'Lapsed', position: 2, color: 'orange' },
        { value: 'CANCELLED', label: 'Cancelled', position: 3, color: 'red' },
        { value: 'EXPIRED', label: 'Expired', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: P_PREMIUM,
      name: 'premiumUgx',
      type: FieldType.NUMBER,
      label: 'Premium (UGX)',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_PLATE,
      name: 'plate',
      type: FieldType.TEXT,
      label: 'Number plate',
      icon: 'IconBadge',
      isSearchable: true,
    },
    {
      universalIdentifier: P_VEHICLE_MAKE,
      name: 'vehicleMake',
      type: FieldType.TEXT,
      label: 'Vehicle make',
      icon: 'IconCar',
    },
    {
      universalIdentifier: P_VEHICLE_MODEL,
      name: 'vehicleModel',
      type: FieldType.TEXT,
      label: 'Vehicle model',
      icon: 'IconCar',
    },
    {
      universalIdentifier: P_SUM_INSURED,
      name: 'sumInsuredUgx',
      type: FieldType.NUMBER,
      label: 'Sum insured (UGX)',
      description:
        'Agreed limit of cover printed on the policy schedule; defaults to the quote vehicle value',
      icon: 'IconShieldCheck',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_BODY_TYPE,
      name: 'bodyType',
      type: FieldType.TEXT,
      label: 'Body type',
      description: 'Vehicle body type on the schedule (falls back to the vehicle record)',
      icon: 'IconCar',
    },
    {
      universalIdentifier: P_ENGINE_CC,
      name: 'engineCc',
      type: FieldType.NUMBER,
      label: 'Engine capacity (c.c.)',
      description: 'Engine capacity on the schedule (falls back to the vehicle record)',
      icon: 'IconEngine',
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: P_SEATING_CAPACITY,
      name: 'seatingCapacity',
      type: FieldType.NUMBER,
      label: 'Seating capacity',
      description: 'Seating capacity on the schedule (falls back to the vehicle record)',
      icon: 'IconUsers',
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: P_TRAINING_LEVY,
      name: 'trainingLevyUgx',
      type: FieldType.NUMBER,
      label: 'Training levy (UGX)',
      description: 'Premium breakdown line on the schedule',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_STICKER_FEES,
      name: 'stickerFeesUgx',
      type: FieldType.NUMBER,
      label: 'Sticker fees (UGX)',
      description: 'Premium breakdown line on the schedule',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_VAT,
      name: 'vatUgx',
      type: FieldType.NUMBER,
      label: 'VAT (UGX)',
      description: 'Premium breakdown line on the schedule',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_STAMP_DUTY,
      name: 'stampDutyUgx',
      type: FieldType.NUMBER,
      label: 'Stamp duty (UGX)',
      description: 'Premium breakdown line on the schedule (S/Duty)',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_TOTAL_PREMIUM,
      name: 'totalPremiumUgx',
      type: FieldType.NUMBER,
      label: 'Total premium (UGX)',
      description:
        'Total due on the schedule; defaults to premium plus the recorded breakdown lines',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_PERIOD_START,
      name: 'periodStart',
      type: FieldType.DATE,
      label: 'Period start',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: P_PERIOD_END,
      name: 'periodEnd',
      type: FieldType.DATE,
      label: 'Period end',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
  ],
});
