import { defineObject, FieldType, NumberDataType } from 'twenty-sdk/define';
import {
  C_CLAIM_REF,
  C_DESCRIPTION,
  C_INCIDENT_DATE,
  C_LOCATION,
  C_POLICY_NO,
  C_PROTECTA_REF,
  C_REPORTER_PHONE,
  C_RESERVE,
  C_STATUS,
  INSURANCE_CLAIM,
} from 'src/constants/universal-identifiers';

export const INSURANCE_CLAIM_UNIVERSAL_IDENTIFIER = INSURANCE_CLAIM;

export default defineObject({
  universalIdentifier: INSURANCE_CLAIM_UNIVERSAL_IDENTIFIER,
  nameSingular: 'insuranceClaim',
  namePlural: 'insuranceClaims',
  labelSingular: 'Insurance claim',
  labelPlural: 'Insurance claims',
  description: 'Motor claim, from first notice to settlement',
  icon: 'IconAlertCircle',
  labelIdentifierFieldMetadataUniversalIdentifier: C_CLAIM_REF,
  fields: [
    {
      universalIdentifier: C_PROTECTA_REF,
      name: 'protectaRef',
      type: FieldType.TEXT,
      label: 'Protecta ref',
      description: 'Claim reference',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: C_CLAIM_REF,
      name: 'claimRef',
      type: FieldType.TEXT,
      label: 'Claim ref',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: C_POLICY_NO,
      name: 'policyNo',
      type: FieldType.TEXT,
      label: 'Policy no',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: C_STATUS,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'REPORTED'",
      options: [
        { value: 'REPORTED', label: 'Reported', position: 0, color: 'yellow' },
        { value: 'ASSIGNED', label: 'Assigned', position: 1, color: 'blue' },
        { value: 'ASSESSED', label: 'Assessed', position: 2, color: 'blue' },
        { value: 'APPROVED', label: 'Approved', position: 3, color: 'green' },
        { value: 'REJECTED', label: 'Rejected', position: 4, color: 'red' },
        { value: 'SETTLED', label: 'Settled', position: 5, color: 'green' },
      ],
    },
    {
      universalIdentifier: C_DESCRIPTION,
      name: 'description',
      type: FieldType.TEXT,
      label: 'Description',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: C_LOCATION,
      name: 'location',
      type: FieldType.TEXT,
      label: 'Location',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: C_INCIDENT_DATE,
      name: 'incidentDate',
      type: FieldType.DATE,
      label: 'Incident date',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: C_RESERVE,
      name: 'reserveUgx',
      type: FieldType.NUMBER,
      label: 'Reserve (UGX)',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: C_REPORTER_PHONE,
      name: 'reporterPhone',
      type: FieldType.TEXT,
      label: 'Reporter phone',
      icon: 'IconPhone',
      isSearchable: true,
    },
  ],
});
