import { defineObject, FieldType, NumberDataType } from 'twenty-sdk/define';
import {
  INSURANCE_POLICY,
  P_PERIOD_END,
  P_PERIOD_START,
  P_PLATE,
  P_POLICY_NO,
  P_PREMIUM,
  P_PROTECTA_REF,
  P_QUOTE_REF,
  P_STATUS,
  P_VEHICLE_MAKE,
  P_VEHICLE_MODEL,
} from 'src/constants/universal-identifiers';

export const INSURANCE_POLICY_UNIVERSAL_IDENTIFIER = INSURANCE_POLICY;

export default defineObject({
  universalIdentifier: INSURANCE_POLICY_UNIVERSAL_IDENTIFIER,
  nameSingular: 'insurancePolicy',
  namePlural: 'insurancePolicies',
  labelSingular: 'Insurance policy',
  labelPlural: 'Insurance policies',
  description: 'Issued Protecta Bode motor policy',
  icon: 'IconShieldCheck',
  labelIdentifierFieldMetadataUniversalIdentifier: P_POLICY_NO,
  fields: [
    {
      universalIdentifier: P_PROTECTA_REF,
      name: 'protectaRef',
      type: FieldType.TEXT,
      label: 'Protecta ref',
      description: 'Policy number',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: P_POLICY_NO,
      name: 'policyNo',
      type: FieldType.TEXT,
      label: 'Policy no',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: P_QUOTE_REF,
      name: 'quoteRef',
      type: FieldType.TEXT,
      label: 'Quote ref',
      icon: 'IconHash',
    },
    {
      universalIdentifier: P_STATUS,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'ACTIVE'",
      options: [
        { value: 'PENDING_PAYMENT', label: 'Pending payment', position: 0, color: 'yellow' },
        { value: 'ACTIVE', label: 'Active', position: 1, color: 'green' },
        { value: 'LAPSED', label: 'Lapsed', position: 2, color: 'orange' },
        { value: 'CANCELLED', label: 'Cancelled', position: 3, color: 'red' },
        { value: 'EXPIRED', label: 'Expired', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: P_PREMIUM,
      name: 'premiumUgx',
      type: FieldType.NUMBER,
      label: 'Premium (UGX)',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: P_PLATE,
      name: 'plate',
      type: FieldType.TEXT,
      label: 'Number plate',
      icon: 'IconBadge',
      isSearchable: true,
    },
    {
      universalIdentifier: P_VEHICLE_MAKE,
      name: 'vehicleMake',
      type: FieldType.TEXT,
      label: 'Vehicle make',
      icon: 'IconCar',
    },
    {
      universalIdentifier: P_VEHICLE_MODEL,
      name: 'vehicleModel',
      type: FieldType.TEXT,
      label: 'Vehicle model',
      icon: 'IconCar',
    },
    {
      universalIdentifier: P_PERIOD_START,
      name: 'periodStart',
      type: FieldType.DATE,
      label: 'Period start',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: P_PERIOD_END,
      name: 'periodEnd',
      type: FieldType.DATE,
      label: 'Period end',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
  ],
});
