import { defineObject, FieldType, NumberDataType } from 'twenty-sdk/define';
import {
  INSURANCE_QUOTE,
  Q_CHANNEL,
  Q_PLATE,
  Q_POLICYHOLDER_PHONE,
  Q_PREMIUM,
  Q_PRODUCT_CODE,
  Q_PROTECTA_REF,
  Q_REFERENCE,
  Q_SHARE_URL,
  Q_STATUS,
  Q_VALID_UNTIL,
  Q_VEHICLE_MAKE,
  Q_VEHICLE_MODEL,
  Q_VEHICLE_VALUE,
} from 'src/constants/universal-identifiers';

export const INSURANCE_QUOTE_UNIVERSAL_IDENTIFIER = INSURANCE_QUOTE;

export default defineObject({
  universalIdentifier: INSURANCE_QUOTE_UNIVERSAL_IDENTIFIER,
  nameSingular: 'insuranceQuote',
  namePlural: 'insuranceQuotes',
  labelSingular: 'Insurance quote',
  labelPlural: 'Insurance quotes',
  description: 'Motor quote: 1.5% of vehicle value, 15-day validity',
  icon: 'IconFileText',
  labelIdentifierFieldMetadataUniversalIdentifier: Q_REFERENCE,
  fields: [
    {
      universalIdentifier: Q_PROTECTA_REF,
      name: 'protectaRef',
      type: FieldType.TEXT,
      label: 'Protecta ref',
      description: 'Quote reference (idempotency key)',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: Q_REFERENCE,
      name: 'reference',
      isUnique: true,
      type: FieldType.TEXT,
      label: 'Quote ref',
      icon: 'IconHash',
      isSearchable: true,
    },
    {
      universalIdentifier: Q_STATUS,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'QUOTED'",
      options: [
        { value: 'DRAFT', label: 'Draft', position: 0, color: 'gray' },
        { value: 'QUOTED', label: 'Quoted', position: 1, color: 'blue' },
        { value: 'ACCEPTED', label: 'Accepted', position: 2, color: 'green' },
        { value: 'EXPIRED', label: 'Expired', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: Q_CHANNEL,
      name: 'channel',
      type: FieldType.SELECT,
      label: 'Channel',
      icon: 'IconChannel',
      defaultValue: "'PORTAL'",
      options: [
        { value: 'PORTAL', label: 'Portal', position: 0, color: 'blue' },
        { value: 'WHATSAPP', label: 'WhatsApp', position: 1, color: 'green' },
        {
          value: 'PARTNER_API',
          label: 'Partner API',
          position: 2,
          color: 'purple',
        },
        { value: 'PHONE', label: 'Phone', position: 3, color: 'orange' },
      ],
    },
    {
      universalIdentifier: Q_PRODUCT_CODE,
      name: 'productCode',
      type: FieldType.TEXT,
      label: 'Product code',
      icon: 'IconPackage',
    },
    {
      universalIdentifier: Q_PLATE,
      name: 'plate',
      type: FieldType.TEXT,
      label: 'Number plate',
      icon: 'IconBadge',
      isSearchable: true,
    },
    {
      universalIdentifier: Q_VEHICLE_MAKE,
      name: 'vehicleMake',
      type: FieldType.TEXT,
      label: 'Vehicle make',
      icon: 'IconCar',
    },
    {
      universalIdentifier: Q_VEHICLE_MODEL,
      name: 'vehicleModel',
      type: FieldType.TEXT,
      label: 'Vehicle model',
      icon: 'IconCar',
    },
    {
      universalIdentifier: Q_VEHICLE_VALUE,
      name: 'vehicleValue',
      type: FieldType.NUMBER,
      label: 'Vehicle value (UGX)',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: Q_PREMIUM,
      name: 'premium',
      type: FieldType.NUMBER,
      label: 'Premium (UGX)',
      icon: 'IconCash',
      universalSettings: { dataType: NumberDataType.BIGINT },
    },
    {
      universalIdentifier: Q_POLICYHOLDER_PHONE,
      name: 'policyholderPhone',
      type: FieldType.TEXT,
      label: 'Policyholder phone',
      icon: 'IconPhone',
      isSearchable: true,
    },
    {
      universalIdentifier: Q_SHARE_URL,
      name: 'shareUrl',
      type: FieldType.TEXT,
      label: 'Share URL',
      icon: 'IconLink',
    },
    {
      universalIdentifier: Q_VALID_UNTIL,
      name: 'validUntil',
      type: FieldType.DATE,
      label: 'Valid until',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
  ],
});
