import { createHash, randomUUID } from 'crypto';
import { coverageAttestation } from '../aml/coverage.js';
import { buildSimplePdf } from '../aml/report.js';
import { buildReportPdf, type ReportDocInput } from '../aml/reportPdf.js';
import { optionalQuery } from './query.js';
import { shortRef } from './ids.js';
import { getOverview } from './overview.js';
import { getSubjectFile, listSubjects } from './subjects.js';
import type { StaffPrincipal } from './staffAuth.js';

export const REPORT_TYPES = [
  { id: 'subject', label: 'Subject report', kind: 'print', description: 'Full evidence pack for one subject.' },
  { id: 'coverage', label: 'Coverage attestation', kind: 'merged', description: 'Proof that approved subjects were screened.' },
  { id: 'funnel', label: 'Onboarding funnel', kind: 'management', description: 'Volumes, pass rates and drop-off.' },
  { id: 'hits', label: 'Hit disposition', kind: 'management', description: 'Every screening hit with outcome.' },
  { id: 'audit', label: 'Audit export', kind: 'regulatory', description: 'Append-only decisions from both modules.' },
  { id: 'sar', label: 'SAR draft', kind: 'regulatory', description: 'Suspicious activity scaffold from the subject file.' },
];

export async function listReports(): Promise<Record<string, unknown>> {
  const stored = await optionalQuery<{
    id: string;
    report_type: string;
    scope: string | null;
    generated_by: string | null;
    created_at: Date;
    size_bytes: number | null;
    status: string;
    display_ref: string | null;
  }>(
    `SELECT id, report_type, scope, generated_by, created_at, size_bytes, status, display_ref
     FROM compliance.generated_reports
     ORDER BY created_at DESC
     LIMIT 50`,
  );
  const coverage = await coverageAttestation().catch(() => null);
  return {
    types: REPORT_TYPES,
    generated: stored.map((r) => ({
      id: r.id,
      ref: r.display_ref || shortRef('RPT', r.id),
      type: r.report_type,
      scope: r.scope,
      generated_at: r.created_at,
      by: r.generated_by || 'system',
      size: r.size_bytes,
      state: r.status,
    })),
    coverage,
    scheduled: [
      { report: 'Coverage attestation', cadence: 'Monthly · 1st', recipients: 'mlro@upsyd.com', format: 'PDF', next: nextFirstOfMonth(), state: 'active' },
      { report: 'Onboarding funnel', cadence: 'Weekly · Mon', recipients: 'ops@upsyd.com', format: 'PDF + CSV', next: nextMonday(), state: 'active' },
    ],
  };
}

const TITLE_LABELS: Record<string, string> = {
  coverage: 'Coverage Attestation',
  funnel: 'Onboarding Funnel Report',
  hits: 'Hit Disposition Report',
  audit: 'Audit Export',
  subject: 'Subject Report',
  sar: 'SAR Draft',
};

function sealFor(data: unknown): string {
  return createHash('sha256').update(JSON.stringify(data, null, 0)).digest('hex');
}

export async function generateReport(opts: {
  type: string;
  subjectId?: string;
  staff: StaffPrincipal;
}): Promise<{ id: string; ref: string; type: string; bytes: Buffer; filename: string; mime: string }> {
  const type = opts.type.toLowerCase();
  if (!REPORT_TYPES.some((t) => t.id === type)) {
    throw Object.assign(new Error(`Unknown report type: ${opts.type}`), { status: 422 });
  }

  let scope = 'all';
  let filename = `${type}.pdf`;
  const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  let doc: ReportDocInput = {
    title: TITLE_LABELS[type] || 'Compliance Report',
    subtitle: 'Generated by the Chunguza compliance console.',
    reference: '',
    generatedAt,
    requestedBy: opts.staff.email,
    verdict: { main: 'REPORT', sub: '', badge: '' },
    sections: [],
    seal: '',
  };

  if (type === 'coverage') {
    const coverage = await coverageAttestation();
    scope = String(coverage.period || 'all');
    const verdict = coverage.passed
      ? { main: 'COVERAGE ATTESTATION: PASSED', sub: 'Every approved subject is linked to a completed screening record.', badge: 'IN COMPLIANCE' }
      : { main: 'COVERAGE GAP: MIGRATION INCOMPLETE', sub: `${coverage.unlinked ?? 0} historical screen(s) still unlinked. Run the backfill.`, badge: 'BACKFILL REQUIRED' };
    doc = {
      title: 'Coverage Attestation',
      subtitle: 'Proof that approved subjects were screened against the OpenSanctions index.',
      reference: shortRef('COV', cryptoRef(coverage)),
      generatedAt,
      requestedBy: opts.staff.email,
      verdict,
      sections: [
        {
          heading: '§ 1. Coverage Summary',
          kind: 'kv',
          pairs: [
            ['Verified Subjects', String(coverage.verified_subjects), 'Historically Screened', String(coverage.historically_screened)],
            ['Linked Subjects', String(coverage.screened_subjects), 'Unlinked (migration gap)', String(coverage.unlinked ?? 0)],
            ['Never Screened', String(coverage.unscreened), 'Migrated', `${coverage.migrated_pct ?? '-'}%`],
            ['Live Coverage', `${coverage.coverage_pct ?? '-'}%`, 'Attestation', coverage.passed ? 'PASSED' : 'INCOMPLETE'],
          ],
        },
        {
          heading: '§ 2. Attestation',
          kind: 'para',
          paragraphs: [String(coverage.note || '')],
        },
      ],
      seal: sealFor({ type: 'coverage', coverage, generatedAt }),
    };
    filename = `coverage-${scope}.pdf`;
  } else if (type === 'funnel') {
    const overview = await getOverview();
    const today = overview.today as Record<string, unknown>;
    doc = {
      title: 'Onboarding Funnel Report',
      subtitle: 'Volumes, pass rates and drop-off across the verification funnel.',
      reference: shortRef('FNL', `${Date.now()}`),
      generatedAt,
      requestedBy: opts.staff.email,
      verdict: { main: `Submitted ${String(today.submitted ?? 0)}`, sub: 'Onboarding funnel snapshot.', badge: 'SNAPSHOT' },
      sections: [
        {
          heading: '§ 1. Today',
          kind: 'kv',
          pairs: [
            ['Submitted', String(today.submitted ?? 0), 'Auto-cleared', String(today.auto_cleared ?? 0)],
            ['In review', String(today.in_review ?? 0), 'Hits', String(today.screening_hits ?? 0)],
            ['Rejected', String(today.rejected ?? 0), 'Screens run', String(today.screens_run ?? 0)],
          ],
        },
        {
          heading: '§ 2. Funnel Stages',
          kind: 'table',
          columns: ['Stage', 'Count'],
          widths: [0.7, 0.3],
          rows: ((overview.funnel as Array<{ stage: string; count: number }>) || []).map((s) => [s.stage, String(s.count)]),
        },
      ],
      seal: sealFor({ type: 'funnel', today, generatedAt }),
    };
    filename = 'funnel.pdf';
  } else if (type === 'hits') {
    const subjects = await listSubjects({ limit: 200 });
    const hits = subjects.items.filter((s) => s.screening !== 'clear' && s.screening !== 'not run');
    scope = `${hits.length} hits`;
    doc = {
      title: 'Hit Disposition Report',
      subtitle: 'Every screening hit with its current outcome.',
      reference: shortRef('HIT', `${Date.now()}`),
      generatedAt,
      requestedBy: opts.staff.email,
      verdict: { main: `${hits.length} HITS`, sub: 'Screening hits requiring disposition.', badge: 'DISPOSITION' },
      sections: [
        {
          heading: '§ 1. Hits',
          kind: 'table',
          columns: ['Reference', 'Subject', 'Screening', 'Risk', 'Decision'],
          widths: [0.18, 0.3, 0.16, 0.12, 0.24],
          rows: hits.slice(0, 40).map((s) => [String(s.ref), String(s.name), String(s.screening), String(s.risk ?? '-'), String(s.decision)]),
        },
      ],
      seal: sealFor({ type: 'hits', count: hits.length, generatedAt }),
    };
    filename = 'hits.pdf';
  } else if (type === 'audit') {
    const decisions = await optionalQuery<{
      decision: string;
      reason: string | null;
      subject_id: string | null;
      created_at: Date;
    }>(`SELECT decision, reason, subject_id, created_at FROM compliance.decisions ORDER BY created_at DESC LIMIT 80`);
    doc = {
      title: 'Audit Export',
      subtitle: 'Append-only decisions from both modules.',
      reference: shortRef('AUD', `${Date.now()}`),
      generatedAt,
      requestedBy: opts.staff.email,
      verdict: { main: `${decisions.length} DECISIONS`, sub: 'Append-only decision log.', badge: 'AUDIT' },
      sections: [
        {
          heading: '§ 1. Decisions',
          kind: 'table',
          columns: ['Date', 'Decision', 'Subject', 'Reason'],
          widths: [0.2, 0.16, 0.24, 0.4],
          rows: decisions.map((d) => [String(d.created_at).slice(0, 19), d.decision, d.subject_id || '', d.reason || '']),
        },
      ],
      seal: sealFor({ type: 'audit', count: decisions.length, generatedAt }),
    };
    filename = 'audit.pdf';
  } else {
    if (!opts.subjectId) {
      throw Object.assign(new Error('subject_id is required for this report type'), { status: 422 });
    }
    const file = await getSubjectFile(opts.subjectId);
    if (!file) throw Object.assign(new Error('Subject not found'), { status: 404 });
    scope = String(file.ref);
    const isSar = type === 'sar';
    doc = {
      title: isSar ? 'SAR Draft' : 'Subject Report',
      subtitle: isSar
        ? 'Suspicious activity scaffold from the subject file.'
        : 'Full evidence pack for one subject.',
      reference: String(file.ref),
      generatedAt,
      requestedBy: opts.staff.email,
      verdict: { main: String(file.name), sub: String(file.country || '-'), badge: isSar ? 'SAR' : 'SUBJECT' },
      sections: [
        {
          heading: '§ 1. Subject Summary',
          kind: 'kv',
          pairs: [
            ['Subject', String(file.name), 'Reference', String(file.ref)],
            ['Country', String(file.country || '-'), 'Verification', String((file.verification as { status?: string }).status)],
            ['Screening', String((file.screening as { status?: string }).status), 'Decision', String((file.decision as { label?: string }).label)],
          ],
        },
        {
          heading: '§ 2. Analyst Note',
          kind: 'para',
          paragraphs: ['This document is a working pack. Analyst verification required.'],
        },
      ],
      seal: sealFor({ type, subject: file.ref, generatedAt }),
    };
    filename = `${file.ref}_${type}.pdf`;
  }

  const bytes = buildReportPdf(doc);
  const id = randomUUID();
  const ref = shortRef('RPT', id);
  await optionalQuery(
    `INSERT INTO compliance.generated_reports (
       id, report_type, scope, payload, generated_by, size_bytes, status, display_ref
     ) VALUES ($1, $2, $3, $4::jsonb, $5, $6, 'ready', $7)`,
    [id, type, scope, JSON.stringify({ doc }), opts.staff.email, bytes.length, ref],
  );
  return { id, ref, type, bytes, filename, mime: 'application/pdf' };
}

function cryptoRef(seed: unknown): string {
  return createHash('sha1').update(JSON.stringify(seed)).digest('hex').slice(0, 12).toUpperCase();
}

export async function getStoredReport(id: string): Promise<{ bytes: Buffer; filename: string } | null> {
  const rows = await optionalQuery<{
    id: string;
    report_type: string;
    payload: unknown;
    display_ref: string | null;
  }>(`SELECT id, report_type, payload, display_ref FROM compliance.generated_reports WHERE id = $1 OR display_ref = $1`, [id]);
  const row = rows[0];
  if (!row) return null;
  const payload = typeof row.payload === 'string' ? JSON.parse(row.payload) : row.payload;
  if (payload && typeof payload === 'object' && (payload as { doc?: ReportDocInput }).doc) {
    return { bytes: buildReportPdf((payload as { doc: ReportDocInput }).doc), filename: `${row.display_ref || row.id}.pdf` };
  }
  const lines = (payload && typeof payload === 'object' && Array.isArray((payload as { lines?: string[] }).lines))
    ? (payload as { lines: string[] }).lines
    : [`Report ${row.display_ref || row.id}`];
  return { bytes: buildSimplePdf(lines), filename: `${row.display_ref || row.id}.pdf` };
}

function nextFirstOfMonth(): string {
  const now = new Date();
  const next = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1, 6, 0, 0));
  return next.toISOString();
}

function nextMonday(): string {
  const now = new Date();
  const day = now.getUTCDay();
  const add = day === 1 ? 7 : (8 - day) % 7 || 7;
  const next = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + add, 5, 0, 0));
  return next.toISOString();
}
