import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFPage,
} from 'pdf-lib';

const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const MARGIN = 56;

const wrap = (
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number,
): string[] => {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [''];
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      line = candidate;
    } else {
      if (line) lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
};

/** Render template text into an A4 PDF certificate. */
export const renderPdf = async (content: string): Promise<Uint8Array> => {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const lines = content.split('\n');
  const title = lines[0] ?? 'Document';
  const body = lines.slice(1);

  const drawFooter = (page: PDFPage, pageNo: number) => {
    const text = `Generated by Protecta Document Generator  ·  page ${pageNo}`;
    const size = 8;
    page.drawText(text, {
      x: MARGIN,
      y: MARGIN / 2,
      size,
      font,
      color: rgb(0.45, 0.45, 0.5),
    });
  };

  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let pageNo = 1;
  let y = PAGE_HEIGHT - MARGIN;

  page.drawText(title, {
    x: MARGIN,
    y,
    size: 18,
    font: bold,
    color: rgb(0.05, 0.1, 0.25),
  });
  y -= 28;

  const maxWidth = PAGE_WIDTH - MARGIN * 2;
  for (const raw of body) {
    const size = 11;
    const lineGap = 16;
    const wrapped = raw.trim().length === 0 ? [''] : wrap(raw, font, size, maxWidth);
    for (const line of wrapped) {
      if (y < MARGIN + 24) {
        drawFooter(page, pageNo);
        page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        pageNo += 1;
        y = PAGE_HEIGHT - MARGIN;
      }
      if (line) {
        page.drawText(line, { x: MARGIN, y, size, font, color: rgb(0, 0, 0) });
      }
      y -= lineGap;
    }
  }
  drawFooter(page, pageNo);

  return doc.save();
};
